# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seats',
            options={},
        ),
        migrations.RemoveField(
            model_name='seats',
            name='booked',
        ),
        migrations.AddField(
            model_name='seats',
            name='row_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seats',
            name='seat_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seats',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seat_type',
            field=models.CharField(max_length=50),
        ),
    ]
